src/lib.rs

docs: Fix typo

---

src/lib.rs

`evaluate` should be `evaluated`, and I think the rest of the sentence reads a little easier this way :)

docs: Small wording adjustment

---

CHANGELOG.md
src/ast.rs
src/compiler.rs
src/parser.rs
src/syntax.rs
tests/inputs/ifexpr.txt
tests/parser-inputs/ifexpr.txt
tests/snapshots/test_parser__parser@ifexpr.txt.snap
tests/snapshots/test_templates__vm@ifexpr.txt.snap

This adds inline ternary if expressions.
Fixes #7

Added inline if expressions

---

Makefile
minijinja/Cargo.toml
minijinja/src/filters.rs
minijinja/src/key.rs
minijinja/src/lib.rs
minijinja/src/value.rs
minijinja/tests/inputs/loop_dictsort.txt
minijinja/tests/snapshots/test_templates__vm@loop_dictsort.txt.snap

This adds support for preserving the order in maps.

Adds a new preserve_order feature to retain map order

---

.github/FUNDING.yml
CHANGELOG.md
examples/recursive-for/Cargo.toml
examples/recursive-for/src/main.rs
minijinja/src/ast.rs
minijinja/src/compiler.rs
minijinja/src/instructions.rs
minijinja/src/parser.rs
minijinja/src/syntax.rs
minijinja/src/vm.rs
minijinja/tests/inputs/loop_recursive.txt
minijinja/tests/snapshots/test_compiler__for_loop.snap
minijinja/tests/snapshots/test_parser__parser@for_loop.txt.snap
minijinja/tests/snapshots/test_parser__parser@for_loop_unpack.txt.snap
minijinja/tests/snapshots/test_templates__vm@debug.txt.snap
minijinja/tests/snapshots/test_templates__vm@loop_recursive.txt.snap
minijinja/tests/test_compiler.rs
minijinja/tests/test_vm.rs

This adds support for `recursive` on for loops.

Added support for recursive for loops

---

CHANGELOG.md
minijinja/src/filters.rs
minijinja/tests/inputs/filters.txt
minijinja/tests/snapshots/test_templates__vm@debug.txt.snap
minijinja/tests/snapshots/test_templates__vm@filters.txt.snap

Added bool filter

---

CHANGELOG.md
minijinja/src/lib.rs
minijinja/src/meta.rs
minijinja/src/source.rs

This ports the Jinja2 meta API to minjinja.
Refs #54

Added meta API

---

CHANGELOG.md
minijinja/src/syntax.rs
minijinja/src/vm.rs
minijinja/tests/inputs/include_choice_none.txt
minijinja/tests/inputs/include_ignore_choice.txt
minijinja/tests/inputs/include_ignore_missing.txt
minijinja/tests/inputs/include_missing.txt
minijinja/tests/snapshots/test_lexer__lexer@not_a_variable.txt.snap
minijinja/tests/snapshots/test_templates__vm@include_choice_none.txt.snap
minijinja/tests/snapshots/test_templates__vm@include_ignore_choice.txt.snap
minijinja/tests/snapshots/test_templates__vm@include_ignore_missing.txt.snap
minijinja/tests/snapshots/test_templates__vm@include_missing.txt.snap

This lets the `include` block try one of multiple choices like in Jinja2.

Added support for choices to include

---

.github/workflows/tests.yml
CHANGELOG.md
README.md
minijinja/Cargo.toml
minijinja/src/environment.rs
minijinja/src/error.rs
minijinja/src/source.rs
minijinja/tests/test_source.rs

I'm still unconvinced if this is something I want to do.
Fixes #54 
Fixes #59

Implement dynamic loading for templates

---

.github/workflows/tests.yml

Fixes an issue with Rust 1.45 on github actions: https://github.com/rust-lang/cargo/issues/10303

Fix CI for 1.45.0

---

examples/dynamic/src/main.rs
minijinja/Cargo.toml
minijinja/src/lib.rs
minijinja/src/syntax.rs
minijinja/src/vm.rs
minijinja/tests/test_templates.rs

This adds the missing `loop.changed()` method.

Add loop.changed()

---

minijinja/src/parser.rs
minijinja/tests/parser-inputs/call.txt
minijinja/tests/parser-inputs/filter.txt
minijinja/tests/snapshots/test_parser__parser@call.txt.snap
minijinja/tests/snapshots/test_parser__parser@filter.txt.snap

Support trailing commas for function calls

---

examples/README.md

links to our examples to avoid needing maintenance on AW updates here

Add link to Actix Web integration example

---

minijinja/src/value/object.rs

Where 'SubObject' is one of 'SeqObject' or 'StructObject'.

Implement 'Object' for 'Arc<T: SubObject>'

---

CONTRIBUTING.md

Pretty small change, but I ran into an issue where the nightly now has many more lints for clippy, so it was failing.
Maybe something to look into in a follow up PR? :crab:

Add notes about toolchain/tests/linting to help contributors

---

COMPATIBILITY.md

I forgot to include this in the PR. 🤦‍♂️

Add compatibility notes for the do tag

---

.github/workflows/tests.yml

Add test for nightly for GitHub Actions

Add test for nightly for GitHub Actions

---

CHANGELOG.md
minijinja/src/defaults.rs
minijinja/src/tests.rs
minijinja/tests/inputs/tests.txt
minijinja/tests/snapshots/test_templates__vm@debug.txt.snap
minijinja/tests/snapshots/test_templates__vm@tests.txt.snap

feat: Added none test

---

CHANGELOG.md
COMPATIBILITY.md
Makefile
benchmarks/Cargo.toml
examples/minimal/README.md
examples/minimal/src/hello.txt
examples/minimal/src/main.rs
minijinja/Cargo.toml
minijinja/src/lib.rs
minijinja/src/syntax.rs
minijinja/src/vm/loop_object.rs
minijinja/src/vm/mod.rs
minijinja/tests/inputs/loop_var.txt
minijinja/tests/snapshots/test_templates__vm@debug.txt.snap
minijinja/tests/snapshots/test_templates__vm@err_bad_nested_subtraction.txt.snap
minijinja/tests/snapshots/test_templates__vm@err_bad_test.txt.snap
minijinja/tests/snapshots/test_templates__vm@err_bad_test_arguments.txt.snap
minijinja/tests/snapshots/test_templates__vm@err_in_include.txt.snap
minijinja/tests/snapshots/test_templates__vm@loop-recursion-error.txt.snap
minijinja/tests/snapshots/test_templates__vm@loop_bad_unpacking.txt.snap
minijinja/tests/snapshots/test_templates__vm@loop_bad_unpacking_wrong_len.txt.snap
minijinja/tests/snapshots/test_templates__vm@loop_var.txt.snap

This feature can be disabled to regain some performance loss.
Fixes #47

Implement previtem/nextitem for loops

---

.github/workflows/build-wheels.yml
minijinja-py/Cargo.toml

WIP config for building wheels.

Add wheel build github action

---

.github/workflows/tests.yml
CHANGELOG.md
minijinja/src/value/mod.rs
minijinja/src/value/serialize.rs
minijinja/src/vm/fuel.rs

Restore compilation on 32bit targets

---

CHANGELOG.md
minijinja/src/compiler/meta.rs
minijinja/tests/inputs/do_closure.txt
minijinja/tests/snapshots/test_templates__vm@do_closure.txt.snap

Fix bad closure generation for do blocks

---

CHANGELOG.md
minijinja/src/compiler/lexer.rs
minijinja/tests/test_templates.rs

Parse float number value in scientific notation

---

Makefile
minijinja/Cargo.toml
minijinja/src/filters.rs
minijinja/src/lib.rs
minijinja/src/tests.rs
minijinja/src/testutils.rs
minijinja/src/vm/state.rs

Turns out that without some utilities it can be really hard to test filters, tests and formatters.

Added test utilitites

---

minijinja/src/value/mod.rs
minijinja/src/value/serialize.rs

Slightly different approach to serializing value handles that does not require creating vectors.

Change internal serialization to use unit variants

---

minijinja/src/environment.rs
minijinja/src/filters.rs
minijinja/src/lib.rs
minijinja/src/utils.rs
minijinja/src/value/argtypes.rs
minijinja/src/value/mod.rs
minijinja/src/vm/mod.rs
minijinja/src/vm/state.rs
minijinja/tests/test_undefined.rs
minijinja/tests/test_value.rs

Implements some of the undefined handling behavior from Jinja2.
Addresses #225 and #226.

Configurable undefined behavior

---

minijinja/src/compiler/meta.rs
minijinja/src/compiler/mod.rs
minijinja/src/expression.rs
minijinja/src/template.rs
minijinja/tests/test_environment.rs
minijinja/tests/test_templates.rs

This adds an API back that returns undeclared variables.
Fixes #248

Added undeclared_variables API

---

CHANGELOG.md
minijinja-py/README.md
minijinja-py/tests/test_basic.py
minijinja/tests/test_templates.rs

Fix a few typos, no functional changes intended.

Fix some typos

---

minijinja/src/error.rs
minijinja/src/output.rs
minijinja/src/template.rs
minijinja/src/vm/context.rs
minijinja/src/vm/mod.rs
minijinja/src/vm/state.rs

Small cleanup to follow up on the changes in #262

Small refactorings for state and output

---

CHANGELOG.md
minijinja/src/compiler/instructions.rs
minijinja/src/lib.rs
minijinja/src/template.rs
minijinja/src/testutils.rs
minijinja/src/vm/context.rs
minijinja/src/vm/mod.rs
minijinja/src/vm/state.rs
minijinja/tests/test_templates.rs

Added eval_to_module

---

minijinja/src/compiler/instructions.rs
minijinja/src/template.rs
minijinja/src/testutils.rs
minijinja/src/value/argtypes.rs
minijinja/src/value/mod.rs
minijinja/src/vm/mod.rs
minijinja/src/vm/state.rs
minijinja/tests/test_templates.rs
minijinja/tests/test_value.rs

Exposes ways to call values via a stable API.
Fixes #267

Expose state and calling as public api

---

minijinja/src/environment.rs
minijinja/src/template.rs
minijinja/src/value/argtypes.rs
minijinja/src/vm/mod.rs

This allows one to create a template directly from a string, not just render it in one go.

Add support for loading templates from strings

---

minijinja/src/loader.rs

Use `Arc<str>` and `Box<str>` internally in the owned templates storage.

Reuse key in owned templates

---

CHANGELOG.md
minijinja/src/compiler/lexer.rs
minijinja/src/compiler/parser.rs
minijinja/src/compiler/tokens.rs
minijinja/src/error.rs
minijinja/tests/test_lexer.rs

This replaces #284 but with pretty much the same intention.

Added exposed error info

---

minijinja-py/src/typeconv.rs
minijinja/src/value/mod.rs
minijinja/tests/test_value.rs

This implements a proper total order for Values with tests.

Implement a functioning total order for values

---

minijinja/src/compiler/lexer.rs
minijinja/tests/snapshots/test_lexer__lexer@raw.txt.snap

Fix incorrect raw block behavior

---

CHANGELOG.md
minijinja-contrib/Cargo.toml
minijinja-contrib/src/filters/datetime.rs
minijinja-contrib/src/filters/mod.rs
minijinja-contrib/src/globals.rs
minijinja-contrib/src/lib.rs
minijinja-contrib/tests/datetime.rs
minijinja-contrib/tests/filters.rs
minijinja/src/filters.rs

Added basic formatting for dates

---

CHANGELOG.md
minijinja-contrib/src/filters/datetime.rs
minijinja-contrib/tests/datetime.rs

Fix datetime iso format formatting for negative offsets

---

CHANGELOG.md
minijinja/src/environment.rs
minijinja/src/vm/mod.rs
minijinja/src/vm/state.rs
minijinja/tests/test_environment.rs

Added `set_path_join_callback` to support path joining like in Jinja2.

Added set_path_join_callback

---

CHANGELOG.md
minijinja/src/compiler/parser.rs
minijinja/src/environment.rs
minijinja/src/loader.rs
minijinja/src/template.rs
minijinja/tests/test_environment.rs

Add support to opt out of trailnig newline trimming

---

minijinja-py/python/minijinja/__init__.py
minijinja-py/src/environment.rs
minijinja-py/src/error_support.rs
minijinja-py/tests/test_basic.py

These were never added to the binding.

Expose missing APIs to Python

---

CHANGELOG.md
minijinja/Cargo.toml
minijinja/src/filters.rs
minijinja/src/value/ops.rs
minijinja/tests/test_filters.rs

Fix an integer overflow on division/abs and neg

---

CHANGELOG.md
minijinja/src/functions.rs
minijinja/tests/inputs/debug.txt
minijinja/tests/snapshots/test_templates__vm@debug.txt.snap

Add support for calling debug() with args

---

minijinja/src/vm/closure_object.rs
minijinja/src/vm/context.rs
minijinja/src/vm/mod.rs

This simplifies the closure tracking logic. Avoids the need of ensuring closures are registered only once.

Refactor closure tracker

---

.github/workflows/build-wheels.yml
.github/workflows/clippy.yml
.github/workflows/rustfmt.yml
.github/workflows/tests.yml
minijinja/src/lib.rs

Configure sscache

---

CHANGELOG.md
minijinja-cli/src/repl.rs
minijinja-py/README.md
minijinja/src/environment.rs
minijinja/src/lib.rs

Most of them found via https://github.com/crate-ci/typos (can easily be integrated into GitHub actions, I'll send another PR if you want 😉).

Fix a few typos

---

CHANGELOG.md
minijinja-cli/src/main.rs

Fix cli failing if repl is disabled

---

examples/dsl/README.md
minijinja/src/error.rs
minijinja/src/value/object.rs

Just helping out with a couple more doc spots.
Thanks for making this library, I'm finding it super useful!
Doug

small docs patch

---

examples/dsl/README.md

Not everyone knows what it means, let's spell it out

docs: spell out DSL acronym

---

Cargo.lock
minijinja-cli/Cargo.toml
minijinja-cli/build.rs
minijinja-cli/src/cli.rs
minijinja-cli/src/main.rs

Fixes #399.
@mitsuhiko, do I need to add further things? Documentation, write a changelog snippet or something like that? Or is it fine for you as is?

Add support for generating completions and a man page for minijinja-cli

---

minijinja-cli/Cargo.toml
minijinja-cli/README.md
minijinja-cli/build.rs
minijinja-cli/src/cli.rs
minijinja-cli/src/main.rs

Allow completions to be generated by command line

---

minijinja-cli/src/cli.rs
minijinja-cli/src/main.rs

This allows one to select a sub-element of the input data.
Refs https://github.com/mitsuhiko/minijinja/discussions/411

Add a --select parameter to cli

---

CHANGELOG.md
minijinja/src/compiler/meta.rs
minijinja/tests/test_macros.rs

Fix a closure handling bug

---

.github/workflows/tests.yml
minijinja/tests/test_vm.rs
scripts/wasmtime-wrapper.sh

I have no idea yet what is going on here but it seems like calls are not working correctly on WASI.

Restore WASI Support

---

Cargo.lock
minijinja/Cargo.toml

This fixes the value tests in the minijinja 2 branch.

Fix value tests

---

minijinja/src/functions.rs
minijinja/src/value/mod.rs
minijinja/src/value/object.rs
minijinja/src/value/ops.rs
minijinja/tests/test_value.rs

Object::len -> Object::enumerator_len

---

minijinja/src/value/argtypes.rs
minijinja/src/value/mod.rs
minijinja/src/value/object.rs
minijinja/src/value/serialize.rs
minijinja/tests/test_value.rs

Better and more intentional Object implementations

---

CHANGELOG.md
minijinja/src/value/ops.rs
minijinja/tests/inputs/adding.txt
minijinja/tests/snapshots/test_templates__vm@adding.txt.snap

Added support for sequence concatenation with the plus operator for better compatibility with Jinja2.

Added support for sequence concatination with +

---

.github/workflows/tests.yml
Cargo.lock
Makefile
minijinja-cli/Cargo.toml
minijinja-cli/src/main.rs
minijinja-cli/tests/test_basic.rs

Add CLI tests

---

CHANGELOG.md
Cargo.lock
examples/line-statements/Cargo.toml
examples/line-statements/README.md
examples/line-statements/src/hello.txt
examples/line-statements/src/main.rs
minijinja/src/compiler/lexer.rs
minijinja/src/syntax.rs
minijinja/tests/lexer-inputs/line-comment.txt
minijinja/tests/lexer-inputs/line-statement.txt
minijinja/tests/snapshots/test_lexer__lexer@line-comment.txt.snap
minijinja/tests/snapshots/test_lexer__lexer@line-statement.txt.snap
minijinja/tests/test_lexer.rs

Added line statement and comment support.

Line statements

---

.github/workflows/build-wheels.yml

Fix build wheels

---

examples/object-using-async/Cargo.toml
minijinja/src/value/object.rs
minijinja/src/value/type_erase.rs

Make this easier to understand for a talk.

Clean up type_erase! macro

---

minijinja/src/value/type_erase.rs

This ensures panic safety for the generated trampolines.

Implement pre-pooping for in type_erase

---

minijinja/src/value/type_erase.rs

Avoid manipulation of refcounts.

Use manuallydrop instead of mem::forget

---

CHANGELOG.md
Cargo.lock
Cargo.lock.msrv
examples/function-using-async/Cargo.toml
minijinja/src/vm/mod.rs
minijinja/tests/test_templates.rs

Fix a bug that caused extends in includes to trigger cycle detection

---

CHANGELOG.md
examples/dsl/src/main.rs
minijinja/src/value/argtypes.rs
minijinja/tests/test_value.rs

This simplifies working with objects in filters and functions.

Implemented &Object and Arc<Object> as ArgType

---

CHANGELOG.md
minijinja/src/value/deserialize.rs
minijinja/tests/test_deserialization.rs

Implements `IntoDeserializer` for `Value` and `&Value`.

Implement IntoDeserializer for Value

---

.github/workflows/tests.yml
Cargo.lock
Cargo.lock.msrv
examples/actix-web-demo/Cargo.toml

Fix nightly builds for examples

---

minijinja/src/filters.rs
minijinja/src/tests.rs
minijinja/src/value/mod.rs
minijinja/src/value/ops.rs
minijinja/tests/test_value.rs

Implement stricter Ord and Eq

---

minijinja-cli/README.md

This was added to homebrew formulas https://github.com/Homebrew/homebrew-core/pull/194348

docs(minijinja-cli): add homebrew installation instructions

---

minijinja-cabi/include/minijinja.h
minijinja-cabi/src/value.rs

Switch to u64 types for value in cabi

---

CHANGELOG.md
minijinja-cli/Makefile
minijinja-cli/generate-syntax-docs.py
minijinja-cli/src/cli.rs
minijinja-cli/src/command.rs
minijinja-cli/src/syntax_help.txt
minijinja-cli/tests/snapshots/test_basic__long_help.snap
minijinja-cli/tests/snapshots/test_basic__short_help.snap

Added `--syntax-help` to show the contents of the syntax help page.

Added syntax help to minijinja-cli

---

.cargo/config.toml
.github/workflows/release.yml
dist-workspace.toml

Try to fix CI

---

CHANGELOG.md
minijinja-cli/Cargo.toml
minijinja-cli/README.md
minijinja-cli/src/cli.rs
minijinja-cli/tests/test_basic.rs

Added order preservation for minijinja-cli

---

COMPATIBILITY.md

Fix typo in COMPATIBILITY.md

---

.github/workflows/tests.yml
CHANGELOG.md
CONTRIBUTING.md
Cargo.lock
Cargo.lock.msrv
README.md
fuzz/Cargo.lock
minijinja-autoreload/Cargo.toml
minijinja-autoreload/README.md
minijinja-cabi/README.md
minijinja-cli/Cargo.toml
minijinja-cli/README.md
minijinja-cli/src/cli.rs
minijinja-contrib/Cargo.toml
minijinja-contrib/README.md
minijinja-embed/Cargo.toml
minijinja-embed/README.md
minijinja-py/README.md
minijinja/Cargo.toml
minijinja/src/utils.rs

Update dependencies and move MSRV to 1.63

---

Cargo.lock
Cargo.lock.msrv
examples/actix-web-demo/Cargo.toml
minijinja-autoreload/Cargo.toml

Dedup some features

---

Cargo.lock
minijinja-py/Cargo.toml
minijinja-py/src/environment.rs
minijinja-py/src/typeconv.rs

This fixes the unsafe `clone`.

Upgrade pyo3 to 0.22

---

UPDATING.md
minijinja-cabi/include/minijinja.h
minijinja-cabi/src/value.rs
minijinja-cli/src/command.rs
minijinja-cli/src/long_help.txt
minijinja-cli/tests/snapshots/test_basic__long_help.snap
minijinja-embed/src/lib.rs
minijinja/src/compiler/codegen.rs
minijinja/src/filters.rs
minijinja/src/lib.rs
minijinja/src/value/mod.rs
minijinja/src/value/object.rs
minijinja/src/value/type_erase.rs

fixed typos

---

README.md

Hope it makes the cut! :smile:

add qsv's use of MiniJinja

---

.github/workflows/typos.yml
CHANGELOG.md
UPDATING.md
_typos.toml
examples/syntax-highlighting/README.md
minijinja-contrib/src/filters/mod.rs
minijinja/src/compiler/parser.rs
minijinja/src/filters.rs

Hi @mitsuhiko ,
I did another round of typo fixes and took the liberty of creating a `_typos.toml` and `typos.yml` GH Action Workflow to automate typo checking going forward.

Typos and typos ci

---

CHANGELOG.md
minijinja-contrib/src/filters/mod.rs
minijinja-contrib/src/lib.rs
minijinja-contrib/tests/filters.rs

This adds the missing |truncate filter.

Added |truncate filter

---

CHANGELOG.md
minijinja/src/value/argtypes.rs

Remove unsafe code from KwargsValues

---

CHANGELOG.md
examples/dynamic-objects/src/main.rs
examples/dynamic-objects/src/template.html
minijinja/src/value/mod.rs
minijinja/src/value/object.rs

Added a new API to create projections of objects into maps.

Added Value::make_object_map

---

COMPATIBILITY.md

From what I understand, #503 has implemented line statements already.

Remove line statements from COMPATIBILITY.md

---

CHANGELOG.md
minijinja/src/compiler/lexer.rs
minijinja/tests/lexer-inputs/lstrip-blocks-keep-inline-space.txt
minijinja/tests/snapshots/test_lexer__lexer@lstrip-blocks-keep-inline-space.txt.snap

This is an AI generated fix.  Will clean this up.
Fixes #672

Fix lstrip_blocks being too eager

---

Cargo.lock
minijinja-contrib/Cargo.toml
minijinja-contrib/src/filters/mod.rs
minijinja-contrib/src/globals.rs
minijinja-contrib/tests/filters.rs
minijinja-contrib/tests/globals.rs

The contrib rand feature still uses 0.8.x.

Upgrade rand for contrib

---

.github/workflows/tests.yml
minijinja-autoreload/Cargo.toml
minijinja-autoreload/src/lib.rs
minijinja-cli/Cargo.toml
minijinja-contrib/Cargo.toml
minijinja-embed/Cargo.toml
minijinja-embed/src/lib.rs
minijinja/Cargo.toml
minijinja/src/compiler/instructions.rs
minijinja/src/compiler/lexer.rs
minijinja/src/tests.rs
minijinja/src/value/mod.rs

Raise MSRV to 1.70.  The goal here is that I can later replace the time crates with jiff for contrib.

Update MSRV to 1.70

---

CHANGELOG.md
Cargo.lock
examples/README.md
minijinja/src/vm/mod.rs
minijinja/src/vm/state.rs
minijinja/tests/test_state.rs

This adds a way for functions and filters to stash away state during rendering.

Added temps feature to state

---

CHANGELOG.md
minijinja-py/Cargo.toml
minijinja-py/tests/test_basic.py

That was forgotten after #557.

Enable loop controls for Python

---

CHANGELOG.md
minijinja/src/value/mod.rs
minijinja/tests/test_value.rs

Fix plain objects not having an absolute order

---

Cargo.lock
minijinja-py/Cargo.toml
minijinja-py/src/environment.rs
minijinja-py/src/error_support.rs
minijinja-py/src/typeconv.rs

Upgrades to latest pyo3 version.

Upgrade pyo3

---

minijinja-py/Cargo.toml
minijinja-py/python/minijinja/__init__.py
minijinja-py/src/error_support.rs
minijinja-py/src/lib.rs
minijinja-py/tests/test_basic.py
minijinja/Cargo.toml
minijinja/src/filters.rs
minijinja/src/utils.rs

Implemented landing pads for Python sort violations

---

CHANGELOG.md
minijinja/src/compiler/meta.rs
minijinja/tests/test_templates.rs

Fix a bug with macros in undeclared_variables

---

CHANGELOG.md
minijinja-py/src/typeconv.rs
minijinja-py/tests/test_basic.py

Correctly handle __bool__ in Python

---

CHANGELOG.md
minijinja-py/src/environment.rs
minijinja/src/environment.rs
minijinja/src/template.rs
minijinja/src/vm/context.rs
minijinja/src/vm/state.rs
minijinja/tests/snapshots/test_templates__vm@debug.txt.snap
minijinja/tests/test_environment.rs
minijinja/tests/test_state.rs

This adds `State::known_variables`.
Refs #715 and #720

Provide a method to list the known variables

---

benchmarks/README.md
minijinja/src/output.rs
minijinja/src/utils.rs
minijinja/src/value/argtypes.rs
minijinja/src/value/mod.rs
minijinja/src/value/object.rs

This PR contains some smaller optimizations that help performance on render.

Micro-optimizations

---

CHANGELOG.md
minijinja-py/python/minijinja/__init__.py
minijinja-py/python/minijinja/__init__.pyi
minijinja-py/tests/templates/base.txt
minijinja-py/tests/templates/includes/foo.txt
minijinja-py/tests/test_basic.py

This adds a path loader to python.

Added load_from_path to python

---

.github/workflows/tests.yml
Cargo.lock
Makefile
README.md
minijinja-js/.cargo/config.toml
minijinja-js/.gitignore
minijinja-js/Cargo.toml
minijinja-js/Makefile
minijinja-js/README.md
minijinja-js/package-lock.json
minijinja-js/package.json
minijinja-js/src/lib.rs
minijinja-js/tests/test_all.mjs

This adds a super basic JavaScript binding which might be enough for some of the use cases.  It's probably not enough to run the playground since this intentionally does not expose the unstable machinery.
This does not yet set up npm publishing.

Add experimental wasm binding

---

Cargo.lock
minijinja-js/Cargo.toml
minijinja-js/src/lib.rs

Probably better not to use it.

Remove wee_alloc

---

CHANGELOG.md
minijinja/src/compiler/lexer.rs
minijinja/src/compiler/tokens.rs
minijinja/tests/test_lexer.rs

Prevent overflows to happen from very large templates

---

CHANGELOG.md
minijinja-cabi/include/minijinja.h
minijinja-cabi/src/utils.rs
minijinja-cabi/src/value.rs

I am not proficient in Rust nor C, please do not hesitate to let me know if I am doing something obviously wrong

minijinja-cabi: Add bytes value constructor

---

CHANGELOG.md
minijinja-contrib/src/rand.rs

Add fallback for atomic u64 to mutex on 32bit systems

---

Cargo.lock
minijinja-cli/tests/snapshots/test_basic__long_help.snap
minijinja-cli/tests/snapshots/test_basic__short_help.snap

Clap did something with snapshots again.

Fix clap snapshots

---

CHANGELOG.md
minijinja-cli/src/output.rs

Correctly handle the permissions of temp files on unix

---

minijinja/src/value/ops.rs

Implement negative slices and fixed byte slices

---

.github/workflows/tests.yml

Add a CI check for next-solver

---

CHANGELOG.md
Cargo.lock
minijinja/src/environment.rs
minijinja/src/filters.rs
minijinja/src/functions.rs
minijinja/src/tests.rs
minijinja/src/value/mod.rs

Backport of #787

---

CHANGELOG.md
minijinja/src/utils.rs

This is an inconsistency to Jinja2.
Fixes #803

Implement missin \xFF and octal handling

---

CHANGELOG.md
CLAUDE.md
minijinja-py/src/typeconv.rs
minijinja-py/tests/test_basic.py
minijinja-py/uv.lock
minijinja/src/expression.rs
minijinja/src/template.rs

Do not swallow all python exceptions when performing attribute lookups
