examples/inheritance.rs
(Thank you very much ! It’s a nice project, the code is short but it already has many features)
I am not sure what the direction for the project is exactly (how much of Jinja2 will be implemented here? All the filters, or a subset ? etc.). It was not crystal clear right away what the feature set was at this point. The example directory feels a bit empty, so I did not suspect so many things were tackled already − it’s only when I browsed the tests that I found… well, the work already done.
Anyway, I’m just adding an extra example with **template inheritance** (one of the killer features IMO of jinja) in order for others to jump right away. It has not much rust code compared to `hello.rs`, the difference is mostly in the Jinja example, so maybe a better direction would be a long example …
=> Added template inheritance example

CHANGELOG.md, Makefile, src/ast.rs, src/compiler.rs, src/instructions.rs, src/parser.rs, src/syntax.rs, src/value.rs, src/vm.rs, tests/inputs/in.txt, tests/parser-inputs/in.txt, tests/snapshots/test_parser__parser@in.txt.snap, tests/snapshots/test_templates__vm@in.txt.snap
This adds support for `value in seq` and `value not in seq`.
Fixes #8
=> Added in/not in expression support

.github/workflows/tests.yml, Makefile, examples/inheritance/src/main.rs, minijinja/Cargo.toml
This restores support for older rust versions when `source` is used. Refs https://github.com/Voultapher/self_cell/issues/30
=> Bump to newer self_cell

minijinja/src/instructions.rs, minijinja/src/key.rs, minijinja/src/value.rs
This started out to fix #1 but also changes the value type to no longer have the shared reference. I think overall this is a much saner internal API in particular because you can move the same `Rc<T>` between different objects (eg: `Key` and `Value`) but it comes with the downsize of overall larger `Value`s. This is caused by `RcType<dyn Object>`.
The way the iteration works now for maps is a bit more wasteful but gets away without `unsafe` which makes me sleep better at night.
Fixes #1
=> Simplier value implementation without unsafe

CHANGELOG.md, minijinja/src/filters.rs, minijinja/src/key.rs, minijinja/src/tests.rs, minijinja/src/value.rs, minijinja/src/vm.rs
Now that value internally has a single repr this primitive business doesn't help much. The code is cleaner internally this way. This should reduce some unnecessary extra complexity and code size.
This also cleans up some oversights that were caused by the use of primitives. Namely that containers that were empty were not considered true and strings and safe strings compared the same accidentally.
=> Deprecate "Primitive" Value API

minijinja/src/compiler.rs, minijinja/src/instructions.rs, minijinja/src/vm.rs, minijinja/tests/inputs/block_super.html, minijinja/tests/inputs/loop_recursive.txt, minijinja/tests/snapshots/test_templates__vm@block_super.html.snap, minijinja/tests/snapshots/test_templates__vm@loop_recursive.txt.snap
This changes the engine so that a direct calls to super and loop
are detected.  This avoids unnecessary double buffering if
necessary.
Refs #45
=> Added opcode for direct super and loop recursion

minijinja/src/filters.rs
This removes the first line of text from the `default` filter which was wrong.
=> Remove eroneous text from documentation

CHANGELOG.md, minijinja/src/ast.rs, minijinja/src/compiler.rs, minijinja/src/environment.rs, minijinja/src/instructions.rs, minijinja/src/parser.rs, minijinja/src/syntax.rs, minijinja/src/vm.rs, minijinja/tests/snapshots/test_parser__parser@include.txt.snap
This adds support for the `include missing` flag on include blocks to make include blocks fail silently if templates are missing.
=> Added support for ignore missing

CHANGELOG.md, minijinja/src/environment.rs, minijinja/src/source.rs, minijinja/tests/test_source.rs
If support for #59 should come it will more convenient to remove the functionality to unload templates. This quite an edge case to support and removing it should be save.
This also removes an unnecessary internal reference where we store the name twice now.
=> Remove remove_template

CHANGELOG.md, minijinja/src/ast.rs, minijinja/src/compiler.rs, minijinja/src/instructions.rs, minijinja/src/meta.rs, minijinja/src/parser.rs, minijinja/src/syntax.rs, minijinja/src/vm.rs, minijinja/tests/inputs/with.txt, minijinja/tests/snapshots/test_parser__parser@with.txt.snap, minijinja/tests/snapshots/test_templates__vm@with.txt.snap, minijinja/tests/test_templates.rs
This adds support for tuple unpacking in with blocks. This also changes how with blocks are compiled to bytecode to better reuse the logic we already have for for loops.
Fixes #65
=> Adds support for tuple unpacking in With blocks

.github/workflows/tests.yml, CHANGELOG.md, Makefile, README.md, minijinja/Cargo.toml, minijinja/src/lexer.rs, minijinja/src/syntax.rs, minijinja/tests/lexer-inputs/raw.txt, minijinja/tests/snapshots/test_lexer__lexer@raw.txt.snap
=> Added support for {% raw %} tag

CHANGELOG.md, minijinja/src/ast.rs, minijinja/src/compiler.rs, minijinja/src/meta.rs, minijinja/src/parser.rs, minijinja/src/syntax.rs, minijinja/src/value.rs, minijinja/src/vm.rs, minijinja/tests/inputs/set.txt, minijinja/tests/parser-inputs/set.txt, minijinja/tests/snapshots/test_parser__parser@set.txt.snap, minijinja/tests/snapshots/test_templates__vm@set.txt.snap
This adds support for `{% set %}` statements.
This fixes #68
=> Added support for `{% set %}`

minijinja/src/filters.rs, minijinja/tests/inputs/filters.txt, minijinja/tests/snapshots/test_templates__vm@filters.txt.snap
I ran `make test` and then `cargo insta review` to verify the changes. I'm not sure if there's anything else that's required. (See below for a note on a line that changed and I'm unsure why.)
=> Add `.`, `-`, and `_` to set of unescaped characters in `urlencode`

minijinja/src/context.rs, minijinja/src/functions.rs, minijinja/src/value.rs
Currently a temporary `BTreeMap` is constructed just to be reconstructed again. With a helper function this can be avoided.
=> Small improvement to how context! works

examples/generate-yaml/Cargo.toml, examples/generate-yaml/README.md, examples/generate-yaml/src/main.rs, examples/generate-yaml/src/template.yaml, minijinja/src/context.rs, minijinja/src/environment.rs, minijinja/src/filters.rs, minijinja/src/syntax.rs, minijinja/src/utils.rs, minijinja/src/vm.rs, minijinja/tests/test_templates.rs
=> Add support for JSON/YAML/JavaScript Escaping

minijinja/src/environment.rs
There is no real point in optimizing the cloning of environments. This carries an unnecessary extra cost we can avoid.
=> Avoid the use of reference counts in environment

minijinja/src/filters.rs, minijinja/src/value.rs
This changes the filter functions in the filters module which take strings to take the value object instead and stringify on demand. This removes some unnecessary clones if strings are passed.
=> Small optimization to string filters to avoid a useless allocation

examples/dynamic/src/main.rs, minijinja/src/environment.rs, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/tests.rs, minijinja/src/value.rs, minijinja/src/vm.rs
This is a change to MiniJinja which changes the traits for filters, functions and tests to take values by reference. This in theory should allow borrowing out of the value (#97) but the lack of GATs in Rust does not actually make this possible yet.
This is a breaking change because some of this functionality is exposed to user code (eg: via `Object`).
=> New Function Traits

minijinja/src/compiler.rs, minijinja/src/filters.rs, minijinja/src/lexer.rs, minijinja/src/parser.rs, minijinja/src/tests.rs, minijinja/src/utils.rs, minijinja/src/value.rs, minijinja/src/vm.rs
This is not needed any longer as our minimal rust version ships it.
=> Remove vendored matches macro

minijinja/Cargo.toml, minijinja/src/environment.rs, minijinja/src/filters.rs, minijinja/src/key/mod.rs, minijinja/src/lib.rs, minijinja/src/macros.rs, minijinja/src/source.rs, minijinja/src/syntax.rs, minijinja/src/tests.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/mod.rs, minijinja/src/value/ops.rs, minijinja/src/value/serialize.rs, minijinja/src/vm.rs, minijinja/tests/test_templates.rs
=> Make sync mode the default and remove non-sync mode

minijinja/src/environment.rs, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/tests.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/mod.rs
This simplifies the function interface and the documentation of it. You no longer need to return results from these functions but values can be returned directly if needed.
=> Simplified function interface

CHANGELOG.md, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/tests.rs, minijinja/src/utils.rs
These traits were not intended to be implemented by users.
Refs #112
=> Seal Filter/Test/Function

CHANGELOG.md, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/tests.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/mod.rs
This now lets a user use remaining arguments on a filter.
=> Added support for remaining arguments

.github/workflows/tests.yml, README.md, examples/dynamic/src/main.rs, minijinja/src/compiler/codegen.rs, minijinja/src/defaults.rs, minijinja/src/environment.rs, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/tests.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/src/vm/mod.rs, minijinja/src/vm/state.rs
This allows borrowing for `&str` and `&Value`. It's a backwards incompatible change because `FunctionArgs::from_values` no longer works. I have hidden these implementations now and added a `from_args` utility as replacement.
This appears to currently require Rust 1.61.0
Fixes #97
=> Add borrow support for filter arguments

benchmarks/inputs/all_elements.html, examples/filters/src/main.rs, examples/filters/src/template.html, minijinja/src/defaults.rs, minijinja/src/environment.rs, minijinja/src/expression.rs, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/lib.rs, minijinja/src/output.rs, minijinja/src/template.rs, minijinja/src/tests.rs, minijinja/src/utils.rs, minijinja/src/value/argtypes.rs, minijinja/src/vm/mod.rs, minijinja/src/vm/state.rs, minijinja/tests/test_vm.rs
This makes the state argument to filters, tests and global functions optional.
Fixes #108
=> Allow optional borrowing of State

minijinja/src/compiler/ast.rs, minijinja/src/compiler/codegen.rs, minijinja/src/compiler/instructions.rs, minijinja/src/compiler/parser.rs, minijinja/src/syntax.rs, minijinja/src/value/ops.rs, minijinja/src/vm/mod.rs, minijinja/tests/inputs/slicing.txt, minijinja/tests/snapshots/test_templates__vm@slicing.txt.snap
Added support for missing slice syntax.
=> Added support for slicing

minijinja-autoreload/src/lib.rs
The `with_fs_watcher` function in `minijinja-autoreload` was not behind the `watch-fs` feature, causing `cargo check --no-default-features` (in the `minijinja-autoreload` crate directory) to fail. This also prevented users of `minijinja-autoreload` from using the auto-reload functionality without bringing in the filesystem-based watching functionality.
=> with_fs_watcher fn should be behind watch-fs feature

minijinja/src/filters.rs, minijinja/src/key/mod.rs, minijinja/src/value/mod.rs, minijinja/src/vm/context.rs, minijinja/src/vm/mod.rs
This adds a way to iterate over values which resolves an omission in the API today that's not great to work with.
Fixes #131
=> Better documentation and iteration interface for value

COMPATIBILITY.md, Makefile, minijinja/Cargo.toml, minijinja/src/compiler/lexer.rs, minijinja/src/lib.rs
This adds support for unicode identifiers which are also supported by Jinja2. As it pulls in an extra dependency, the `unicode` feature needs to be enabled.
=> Added support for unicode identifiers

minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/src/vm/loop_object.rs, minijinja/src/vm/macro_object.rs
This changes the method to return an iterator. This iterator here is over `&str` which I wonder if that is generic enough. It at least feels like it should be somewhat easy to fulfill but obviously there might be corner cases where this is non trivial. However changing the item to a `Cow<'_, str>` is not quite as easy without making some more changes throughout the system.
Fixes #137
=> Change the Object::attributes method to return an iterator

minijinja/src/value/object.rs
As in the title. As a result of this `impl`, we can implement `Object` on `T` and get it for free on `Arc`. Without this, we need a wrapper type.
=> Implement 'Object' for 'Arc<T: Object>'

minijinja/src/compiler/ast.rs, minijinja/src/compiler/codegen.rs, minijinja/src/compiler/instructions.rs, minijinja/src/compiler/meta.rs, minijinja/src/compiler/parser.rs, minijinja/src/output.rs, minijinja/src/vm/context.rs, minijinja/src/vm/mod.rs, minijinja/src/vm/state.rs, minijinja/tests/inputs/block_scope_extends.txt, minijinja/tests/inputs/err_extends_twice.txt, minijinja/tests/inputs/extends_set.txt, minijinja/tests/inputs/macro_extends.txt, minijinja/tests/inputs/refs/layout_with_var.txt, minijinja/tests/inputs/refs/var_referencing_layout.txt, minijinja/tests/snapshots/test_templates__vm@block_scope_extends.txt.snap, minijinja/tests/snapshots/test_templates__vm@debug.txt.snap, minijinja/tests/snapshots/test_templates__vm@err_extends_twice.txt.snap, minijinja/tests/snapshots/test_templates__vm@err_self_extends.txt.snap, minijinja/tests/snapshots/test_templates__vm@extends_set.txt.snap, minijinja/tests/snapshots/test_templates__vm@macro_extends.txt.snap
This aligns the runtime behavior of `{% extends %}` with Jinja2. Fixes #136 
Specifically top level assignments (or macro declarations) still execute before the parent template is included. This behavior is somewhat dubious because it can lead to unexpected results if the parent template uses the same variable name. Longer term it might be wise to correct this, but for now this is an acceptable tradeoff.
This also removes `{% block %}` if the `multi-template` feature is not turned on which was an accidental omission.
=> Align extends semantics with Jinja2

minijinja/src/value/mod.rs, minijinja/src/vm/context.rs
Since the value is already `Arc`ed there are cases where it's nice to be able to hold on to them.
Refs #139
=> Expose a way to hold on to the arc on object creation

minijinja/src/filters.rs, minijinja/src/key/mod.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/mod.rs, minijinja/src/value/ops.rs, minijinja/src/value/serialize.rs
=> Added misaligned i128/u128

minijinja/src/defaults.rs, minijinja/src/environment.rs
=> Use 'Cow<str>' for names of added items

minijinja/src/vm/mod.rs, minijinja/src/vm/state.rs, minijinja/tests/snapshots/test_templates__vm@debug.txt.snap, minijinja/tests/test_templates.rs
Corollary to #146: so you can retrieve the dynamic name without having to clone it into the filter/function/test.
=> Expose the name of the currently called item

examples/dynamic/src/main.rs, examples/dynamic/src/template.html, examples/load-lazy/src/main.rs, minijinja/src/error.rs, minijinja/src/filters.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/src/value/ops.rs, minijinja/src/vm/loop_object.rs, minijinja/src/vm/macro_object.rs, minijinja/src/vm/mod.rs, minijinja/tests/snapshots/test_templates__vm@err_bad_filter.txt.snap, minijinja/tests/snapshots/test_templates__vm@loop_bad_unpacking.txt.snap, minijinja/tests/snapshots/test_templates__vm@loop_over_non_iterable.txt.snap, minijinja/tests/test_value.rs
This changes the object interface to support both structs and sequences with the possibility to add extra behavior (eg: arbitrary key maps) at a future point. There are some challenges with this design however.
**Issues:**
These are probably something I need to accept:
* `impl<'a, T: ArgType<'a, Output = T>> ArgType<'a> for Vec<T>` cannot be implemented to support these new dynamic sequences because the lifetime constraints cannot be enabled. Restrict?
**Things to resolve:**
This is stuff that can be fixed:
Refs #147
=> Implemented Revamped Object Model

minijinja/src/environment.rs
An alternative to 'Environment::render_str()' which allows specifying the rendered template's name.
=> Add 'Environment::render_named_str()'

minijinja/src/compiler/codegen.rs, minijinja/src/compiler/instructions.rs, minijinja/src/compiler/parser.rs, minijinja/src/error.rs, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/key/mod.rs, minijinja/src/syntax.rs, minijinja/tests/snapshots/test_parser__parser@max-recursion-expr.txt.snap, minijinja/tests/snapshots/test_parser__parser@max-recursion-tags.txt.snap, minijinja/tests/snapshots/test_parser__parser@max-recursion.txt.snap
[`codespell --ignore-words-list=crate,nd,ser,unkown,worl --skip="./.*,*.ai"`](https://pypi.org/project/codespell)
=> Fix typos discovered by codespell

benchmarks/Cargo.toml, benchmarks/askama.toml, benchmarks/benches/comparison.rs, benchmarks/inputs/comparison/askama.html, benchmarks/inputs/comparison/askama_footer.html
As suggested on mastdon, I added `askama` to the list of benched frameworks. As `askama` is compiling templates at compile time, I didn't add it into the template "compilation" benches.
Here are the results I got locally:
```
cmp_compile/minijinja   time:   [7.3282 µs 7.3511 µs 7.3800 µs]
cmp_compile/tera        time:   [71.494 µs 72.032 µs 72.729 µs]
cmp_compile/liquid      time:   [54.202 µs 55.787 µs 57.225 µs]
cmp_compile/handlebars  time:   [74.124 µs 74.722 µs 75.402 µs]
cmp_render/minijinja    time:   [8.5798 µs 8.6515 µs 8.7736 µs]
cmp_render/tera         time:   [12.118 µs 12.206 µs 12.306 µs]
cmp_render/liquid       time:   [17.483 µs 17.739 µs 18.032 µs]
cmp_render/handlebars   time:   [10.168 µs 10.229 µs 10.296 µs]
cmp_render/askama       time:   [2.3692 µs 2.3902 µs 2.4139 …
```
=> Add benchmark for askama

.github/workflows/tests.yml
The current curl to bash installer from wasmtime sometimes produces a 404 error because it reads an invalid response from the API. Instead of pulling in the latest it's possible to just pin on a stable binary instead.
=> Try to pin wasmtime binary as installer is buggy

CHANGELOG.md, fuzz/Cargo.toml, fuzz/fuzz_targets/render.rs, minijinja/Cargo.toml, minijinja/src/environment.rs, minijinja/src/error.rs, minijinja/src/filters.rs, minijinja/src/lib.rs, minijinja/src/vm/fuel.rs, minijinja/src/vm/loop_object.rs, minijinja/src/vm/mod.rs, minijinja/src/vm/state.rs, minijinja/tests/test_fuel.rs
In order to better sandbox the engine, this adds the ability to track fuel consumption during execution. Once the engine runs out of fuel, an error is produced.
=> Fuel Tracking

minijinja-stack-ref/src/lib.rs
Was failing with these:
```rust
---- src/lib.rs - can_reborrow (line 260) stdout ----
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `,`
--> src/lib.rs:276:61
|
19 |                 Some(Value::from_serializable(&self.values)),
|                                                             ^ expected one of `.`, `;`, `?`, `}`, or an operator
error: aborting due to previous error
Couldn't compile the test.
---- src/lib.rs - (line 72) stdout ----
error[E0425]: cannot find function `reborrow` in this scope
--> src/lib.rs:98:30
|
29 |             "config" => Some(reborrow(self, |slf, scope| {
|                              ^^^^^^^^
|
help: try calling `reborrow` as a method
|
29 ~             "config" => Some(self.reborrow(|slf, scope| {
30 + …
```
=> Fix doc tests failing on nightly

CHANGELOG.md, minijinja/src/compiler/lexer.rs, minijinja/tests/lexer-inputs/whitespace.txt, minijinja/tests/snapshots/test_lexer__lexer@raw.txt.snap, minijinja/tests/snapshots/test_lexer__lexer@whitespace.txt.snap
The previous implementation had various bugs and limitations with regards to whitespace trimming.
Fixes #186
=> Fixes bugs with the whitespace trimming behavior

minijinja-py/.gitignore, minijinja-py/Cargo.toml, minijinja-py/README.md, minijinja-py/hello.py, minijinja-py/python/minijinja/__init__.py, minijinja-py/src/environment.rs, minijinja-py/src/lib.rs, minijinja-py/src/typeconv.rs, minijinja-py/tests/test_basic.py
* The first commit changes the import name from `minijinja_py` to `minijinja` and move the extension module to `minijinja._lowlevel`
* The second commit upgrades pyo3 to 0.18.0
=> Tweak Python binding

minijinja-py/src/typeconv.rs, minijinja-py/tests/test_security.py
Dicts were accidentally prevented from having underscore prefixed keys accessed. This security protection was supposed to only kick in for objects.
Fixes #196
=> Allow access to underscore prefixed values in dicts

benchmarks/Cargo.toml, benchmarks/README.md, minijinja/src/compiler/codegen.rs, minijinja/src/environment.rs, minijinja/src/filters.rs, minijinja/src/template.rs
This calculates the number of bytes of raw template output instructions to set a initial buffer capacity when rendering into a string. This is not a real lower bound, but it's one in probably most cases.
Results in a tiny speedup.
Refs #203
=> Add a size hint for the initial buffer size

minijinja/Cargo.toml, minijinja/src/value/mod.rs, minijinja/src/value/serialize.rs, minijinja/tests/test_templates.rs
Changes the format so that `#[serde(flatten)]` of a `Value` fails with an error, than silently doing the wrong thing. Unfortunately this is not resolvable without changes in serde itself.
Previously you this would flatten out the internal handle which is not what you want, now it fails with an error.
Refs #222
=> Change internal serialization format to fail flattening of values

CHANGELOG.md, minijinja-py/README.md, minijinja-py/python/minijinja/__init__.py, minijinja-py/src/environment.rs, minijinja-py/tests/test_basic.py
This adds a new `finalizer` callback to the Python API that can be used to modify the value before it is rendered with the formatter. This is not quite the same as the formatter system in MiniJinja but it better resembles how this works in Jinja2.
Refs https://github.com/mitsuhiko/minijinja/discussions/237
=> Improved Callbacks for Python

minijinja/src/tests.rs
I think the example codes are misleading and invalid:
```
syntax error: unexpected string, expected end of variable block
```
=> Fix startingwith/endingwith docs

minijinja-autoreload/src/lib.rs
On Windows, when a file is saved, it sends an EventKind::Modify(ModifyKind::Any) event, which was not currently being handled by the AutoReloader Notifier.
See https://github.com/mitsuhiko/minijinja/issues/247
=> Fix an issue with autoreloading on file save with Windows.

.github/workflows/tests.yml, minijinja/src/vm/fuel.rs
Fuel feature fails to compile if `macros` and `multi_template` features are not enabled too.
=> ci: add test for fuel feature

minijinja-contrib/src/filters.rs
One of the examples for using the pluralize filter had the wrong variable name.
=> Update documentation in filters.rs

minijinja-py/Makefile, minijinja-py/pyproject.toml
This showcases https://github.com/PyO3/maturin/pull/1462 / https://github.com/PyO3/maturin/issues/1461: We don't need to activate the venv anymore for `maturin develop`, a normal `.venv/bin/maturin develop` now uses it automatically just like the other tools do (it's technically different from what e.g. pytest does, but from a user perspective it works the same, so i think it's an appropriate solution).
=> Use maturin==0.15.1 to fix venv handling

minijinja-py/Cargo.toml, minijinja-py/pyproject.toml
maturin configuration options moved to `pyproject.toml` in 0.15.
=> Fix python module configuration with maturin 0.15

minijinja/src/compiler/meta.rs, minijinja/src/expression.rs, minijinja/src/template.rs, minijinja/tests/test_environment.rs, minijinja/tests/test_templates.rs
Followup to #248 which is a tiny bit more useful as it now supports nested identifier tracking.
=> Support nested assignment tracking

minijinja/src/compiler/codegen.rs, minijinja/src/compiler/instructions.rs, minijinja/src/vm/fuel.rs, minijinja/src/vm/mod.rs
The `RenderParent` opcode is in some ways an unnecessary leftover. When looking at how to implement #260 I realized the engine simplifies slightly by not having this opcode.
=> Kill RenderParent opcode

minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/value/argtypes.rs
This significantly improves the handling of keyword args in the engine.
* `Kwargs::from_args` is removed for just `from_args`
* Fixed `dict()` accidentally returning kwargs instead of a native map
* Added support to allow unpacking to `&[Value]` before `Kwargs`.
=> Improve handling of Kwargs

minijinja/src/environment.rs, minijinja/src/loader.rs, minijinja/src/template.rs, minijinja/src/vm/mod.rs, tools/minijinja-dis/src/main.rs
Now that source is fully gone, no reason to hold on to confusing terminology.
=> Rename the internal types and API away from store

CHANGELOG.md, examples/template-module/README.md, minijinja/src/environment.rs, minijinja/src/lib.rs, minijinja/src/loader.rs, minijinja/src/template.rs, minijinja/src/vm/state.rs
`TemplateModule` is a bit too inviting of a name. You basically never need to name this type, so having it a less obvious name is probably better here. The type people need to care about is just `Template`.
=> Improve docs and TemplateModule -> Module

CHANGELOG.md, minijinja/src/value/mod.rs, minijinja/tests/inputs/indexing.txt, minijinja/tests/inputs/slicing.txt, minijinja/tests/snapshots/test_templates__vm@indexing.txt.snap, minijinja/tests/snapshots/test_templates__vm@slicing.txt.snap
In the rattler-build project we came across the issue that we couldn't index into strings. Not sure if this is intentional or not, but this PR attempts to fix it (if it wasn't intentional).
https://github.com/prefix-dev/rattler-build/issues/149
I tested it and it works, but before working further on this I wanted to check if this is desired in minijinja or not.
Also `{{ name | first }}` seems to work fine for strings.
=> allow indexing into strings

CHANGELOG.md, minijinja/src/compiler/parser.rs, minijinja/tests/parser-inputs/include.txt, minijinja/tests/snapshots/test_parser__parser@include.txt.snap
This does not do anything, but if a Jinja2 template uses this it will work in MiniJinja now.
=> Added with/without context syntax support

CHANGELOG.md, minijinja/src/filters.rs, minijinja/src/value/mod.rs, minijinja/tests/test_value.rs
Note that `Ord` is lying. It does not implement total ordering but I do not believe that is an issue for how value is implemented. It makes it a lot more convenient to use both in the engine and as a user.
This is in parts in anticipation of experiments for #294
=> Implement improved PartialOrd and Ord for Value

CHANGELOG.md, examples/merge-context/src/main.rs, minijinja/src/filters.rs, minijinja/src/macros.rs, minijinja/src/value/merge_object.rs, minijinja/src/value/mod.rs, minijinja/tests/test_macros.rs
This adds the ability to merge map values with the `context!` macro.
Fixes #316
=> Added merge functionality to context! macro

CHANGELOG.md, examples/README.md, examples/deserialize/Cargo.toml, examples/deserialize/README.md, examples/deserialize/src/main.rs, examples/deserialize/src/path.txt, minijinja/src/error.rs, minijinja/src/lib.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/deserialize.rs, minijinja/src/value/mod.rs, minijinja/tests/test_deserialization.rs, minijinja/tests/test_value.rs
`Value` objects can now be conveniently converted to types that can deserialize.
Fixes #323
=> Implement deserializers for values and ViaDeserialize

CHANGELOG.md, minijinja/src/vm/macro_object.rs, minijinja/src/vm/mod.rs, minijinja/src/vm/state.rs, minijinja/tests/test_macros.rs
This does not make macros callable from other states, but it avoids a panic.
Refs #329
=> Prevent macros from panicking when called with wrong state

minijinja/src/filters.rs
First of all, thanks a lot for creating and sharing Jinja2 and MiniJinja!
This pull request fixes the doc example of `unique` filter. It also deletes the duplicated line of comment.
I verified that `unique` filter is case sensitive with the following tests.
```
#[test]
fn test_unique_ok() {
let mut env = Environment::new();
env.add_template(
"test.html",
"{% autoescape 'none' %}{{ ['foo', 'bar', 'foobar', 'foobar']|unique }}{% endautoescape %}",
)
.unwrap();
let tmpl = env.get_template("test.html").unwrap();
assert_eq!(tmpl.render(()).unwrap(), "[\"foo\", \"bar\", \"foobar\"]");
}
#[test]
fn test_unique_is_case_sensitive() {
let mut env = Environment::new();
env.add_template(
"test.html",
"{% autoescape 'none' %}{{ ['foo', 'bar', 'foobar', 'FooBar']|unique }}{% endautoescape %}",
) …
```
=> Fix filter doc example

minijinja/src/filters.rs
I suppose it was copied from round filter and left as is.
=> Fix error message of abs filter

CHANGELOG.md, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/tests/test_value.rs
This adds support for downcasting objects directly created from `Value::from_seq_object` and `Value::from_struct_object`.
=> Improve downcast to support SeqObject/StructObject

.github/workflows/tests.yml, CHANGELOG.md, minijinja/Cargo.toml, minijinja/src/environment.rs, minijinja/src/lib.rs, minijinja/src/template.rs, minijinja/src/vm/context.rs, minijinja/src/vm/mod.rs, minijinja/src/vm/state.rs, minijinja/tests/test_vm.rs, scripts/wasmtime-wrapper.sh
There are templates out there which require excessive amounts of recursion.  This adds an optional `stacker` feature that allows raising of the max recursion limit to effectively unlimited by automatically growing the stack as needed.  Note that this only raises the runtime limit. The parser still enforces a maximum recursion while parsing.
=> Add stacker support for very large recursion

.github/workflows/build-wheels.yml, .github/workflows/clippy.yml, .github/workflows/rustfmt.yml, .github/workflows/tests.yml
The main change here is that it updates the node version used on the runner to keep ahead of their deprecation policies.
=> ci: Update to actions/checkout@v4.

minijinja-stack-ref/src/lib.rs, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/lib.rs, minijinja/src/value/mod.rs
These are described at: https://doc.rust-lang.org/rustdoc/lints.html#redundant_explicit_links
=> docs: Fix rustdoc::redundant_explicit_links warnings.

CHANGELOG.md, minijinja-cli/src/main.rs
At work, I had this requirement where I wanted the output to be produced without any newline. This is similar to how `echo` has the option `-n`.
Also, thanks for creating minijinja among other things. :-)
=> Ability to provide --no-newline option to skip newline

CHANGELOG.md, minijinja/src/environment.rs, minijinja/src/expression.rs, minijinja/src/loader.rs, minijinja/tests/test_environment.rs
This allows expressions to be compiled without requiring a held lifetime.
=> Added Environment::compile_expression_owned

minijinja/src/compiler/parser.rs, minijinja/src/environment.rs, minijinja/src/lib.rs, minijinja/src/loader.rs, minijinja/src/template.rs
This adds an internal `TemplateConfig` abstraction which holds load time template configuration. The motivation here is that the `Template` wrapper no longer holds any information. This way it would be possible to detach and later re-attach an environment to a template which can enable external caching of template objects easier.
=> Introduce internal template config abstraction

CHANGELOG.md, minijinja/src/filters.rs, minijinja/tests/inputs/filters.txt
This is a much more useful behavior.
=> urlencode now correctly skips over none/undefined

CHANGELOG.md, minijinja/src/functions.rs, minijinja/src/value/argtypes.rs, minijinja/tests/inputs/dict.txt, minijinja/tests/snapshots/test_templates__vm@dict.txt.snap
This lets the `dict()` call merge in the keyword arguments. It also makes the function work with non native dict objects.
=> Added merging functionality to dict function

CHANGELOG.md, Cargo.lock, minijinja-cli/Cargo.toml, minijinja-cli/src/main.rs
This adds a parameter to write into a target file. This also permits in-place replacements of the input template as the write happens at the very end.
Fixes #404
=> Implement --output for minijinja-cli

COMPATIBILITY.md
Jinja2 provides the [loop controls](https://jinja.palletsprojects.com/en/3.1.x/extensions/#loop-controls) extension, which adds support for the `{% continue %}` and `{% break %}` tags. However, these are currently not supported in minijinja.
=> Document the missing support for {% continue %} and {% break %}

minijinja/src/functions.rs
This PR intends making it easier for somebody that wants to `env.add_function` to figure out how their arguments for the custom functions should look like.
It adds information about the `ArgType` trait that the arguments have to implement, and also adds an example with `ViaDeserialize` to show how you can access your custom types from that function.
=> Added documentation for argument type on functions module

minijinja-stack-ref/src/lib.rs
This PR fixes a few warnings related to ambiguous pointer comparisons in the `minijinja-stack-ref/src/lib.rs` file.
It applies the suggested fix by the compiler.
All tests have passed.
=> Fixed warnings in stack-ref lib.rs

CHANGELOG.md, minijinja-cli/src/main.rs, minijinja/src/error.rs
Useful utility to quickly render the debug info as the error display does.
=> Expose a display_debug_info method

CHANGELOG.md, minijinja-cli/src/cli.rs, minijinja-cli/src/main.rs
This adds a way to restrict template includes to a given path. Can be supplied multiple times.
Fixes #431
=> Add --safe-path to restrict template loading from unsafe paths

CHANGELOG.md, minijinja-py/src/environment.rs, minijinja-py/src/error_support.rs, minijinja-py/src/state.rs, minijinja-stack-ref/src/lib.rs, minijinja/src/output.rs, minijinja/src/value/mod.rs
Fixes some clippy lints and a warning introduced in 1.77.
Refs https://github.com/rust-lang/rust/issues/114447
=> Make clippy and rustc happy for rust 1.77

CHANGELOG.md, minijinja/src/value/mod.rs
The fallthrough of `call_method` in `Value` incorrectly returned the wrong error.
=> Emit UnknownMethod instead of InvalidOperation

CHANGELOG.md, minijinja/src/environment.rs, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/tests/test_environment.rs
This allows a user to implement methods that are otherwise not available on objects:
```rust
use minijinja::value::{ValueKind, from_args};
use minijinja::{Error, ErrorKind};
env.set_unknown_method_callback(|state, value, method, args| {
if value.kind() == ValueKind::Map && method == "items" {
let _: () = from_args(args)?;
state.apply_filter("items", &[value.clone()])
} else {
Err(Error::new(
ErrorKind::UnknownMethod,
"object has no method named {name}",
))
}
});
```
Fixes #438
=> Add support for unknown_method_callback

CHANGELOG.md, minijinja-cli/src/main.rs, minijinja/src/compiler/lexer.rs, minijinja/src/lib.rs, minijinja/tests/test_lexer.rs
=> Add the tokenize function back

examples/dynamic-objects/src/main.rs, examples/self-referential-context/src/main.rs, examples/undefined-tracking/src/main.rs, examples/value-tracking/src/main.rs, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/utils.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/deserialize.rs, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/src/value/ops.rs, minijinja/src/vm/context.rs, minijinja/src/vm/macro_object.rs, minijinja/src/vm/mod.rs, minijinja/tests/snapshots/test_templates__vm@loop_bad_unpacking.txt.snap, minijinja/tests/test_environment.rs, minijinja/tests/test_value.rs
This is a work in progress PR for the changes mentioned in #456.
It changes the object protocol so that custom iterators are possible. There is still a lot of duplication and some of the code paths are pretty gnarly. In particular I think it might be better to try to implement `Object::from_iterator` again (#457) with some proper tests to ensure that all code paths behave as intended.
TODO:
Follow up for later:
* This changes the system to buffer for `|reverse` which seems suboptional
* Is there a way to get rid of the `Box<dyn Iterator>` for a concrete type?
Fixes #453
Fixes #455
Fixes #456
Fixes #454
Fixes #459
=> New iterator interface

examples/dynamic-context/src/main.rs, examples/dynamic-objects/src/main.rs, examples/self-referential-context/src/main.rs, examples/undefined-tracking/src/main.rs, examples/value-tracking/src/main.rs, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/deserialize.rs, minijinja/src/value/merge_object.rs, minijinja/src/value/mod.rs, minijinja/src/value/namespace_object.rs, minijinja/src/value/object.rs, minijinja/src/value/ops.rs, minijinja/src/vm/closure_object.rs, minijinja/src/vm/loop_object.rs, minijinja/src/vm/macro_object.rs, minijinja/tests/test_deserialization.rs, minijinja/tests/test_templates.rs, minijinja/tests/test_value.rs
This implements the concept of an `Enumerator` as an alternative to the current `Enumeration` system as outlined in https://github.com/mitsuhiko/minijinja/issues/456#issuecomment-2030630560.
It's mostly what's there with some minor differences that I ran into during implementation:
* `iter` -> `try_iter` as an extension method
* I ended up adding `Enumerator::NonEnumerable` which I believe fits nicer
* `Enumerator::Seq` instead of `Enumerator::Sequential`
Personally I quite like this, but I would like to play with this in practice more first.
It still retains `Value::from_iterator` which I think can be seen as a mistake but I want to fix this later.  It also renames `mapped_enumeration` to `mapped_enumerator`.
=> Implement enumerators

examples/dynamic-objects/src/main.rs, minijinja/src/filters.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/src/value/ops.rs, minijinja/tests/test_value.rs
This implements more efficient reversing by avoiding to buffer in most cases.  It also makes the slice operator not allocate needlessly any more.  Additionally there are some API changes to align this better with the intended user experience:
* `Value::from_iterator` -> `Value::make_one_shot_iterator`
* `Value::from_object_iter` -> `Value::make_object_iterable`
* `Value::make_iterable` -> Similar to `from_object_iterable` but without the borrowing
* Expose `Value::reverse`
* `ObjectExt::mapped_rev_enumerator` -> Like `mapped_enumerator` but for efficient reversing
Fixes #464 and #462
=> Add efficient reversing and slicing

minijinja/src/environment.rs, minijinja/src/loader.rs, minijinja/tests/test_environment.rs
A mechanism to iterate over all loaded templates
=> Add 'Environment::templates()' iterator

CHANGELOG.md, examples/dsl/src/main.rs, examples/dynamic-objects/src/main.rs, minijinja/src/defaults.rs, minijinja/src/environment.rs, minijinja/src/tests.rs, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/src/vm/loop_object.rs, minijinja/tests/inputs/tests.txt, minijinja/tests/snapshots/test_templates__vm@debug.txt.snap, minijinja/tests/snapshots/test_templates__vm@tests.txt.snap, minijinja/tests/test_environment.rs
This adds the iterable test from Jinja2 and adds a default `UnknownMethod` error message.
=> Added the iterable test from Jinja2

minijinja/src/filters.rs, minijinja/src/utils.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/deserialize.rs, minijinja/src/value/mod.rs, minijinja/src/value/ops.rs, minijinja/src/value/serialize.rs, minijinja/src/vm/macro_object.rs, minijinja/src/vm/mod.rs
Now that the object interface is based on `Value` objects everywhere, the small string optimization is meaningful as it cuts down on a lot of allocations for attribute and variable lookups.
Fixes #477
=> Store short strings inline in Value

CHANGELOG.md, examples/deserialize/src/main.rs, examples/load-lazy/src/main.rs, examples/load-resource/src/main.rs, minijinja-stack-ref/src/lib.rs, minijinja/src/expression.rs, minijinja/src/macros.rs, minijinja/src/template.rs, minijinja/src/value/mod.rs, minijinja/tests/test_deserialization.rs, minijinja/tests/test_value.rs, minijinja/tests/test_vm.rs
This introduces the same API as in MiniJinja 2.x to make it easier to upgrade.
=> Introduce Value::from_serialize for 1.x

CHANGELOG.md, minijinja/src/compiler/meta.rs, minijinja/tests/test_templates.rs
There was a bug that caused an endless loop.
Fixes #484
=> Fix endless loop in undeclared_variables

CHANGELOG.md, examples/dynamic-objects/src/main.rs, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/tests/test_value.rs
Introduces the API with the same name from 2.x
=> Introduce Value::make_one_shot_iterator in 1.x

CHANGELOG.md, minijinja/src/error.rs, minijinja/src/filters.rs, minijinja/src/lib.rs, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/src/value/serialize.rs, minijinja/src/vm/context.rs, minijinja/src/vm/mod.rs, minijinja/tests/test_deserialization.rs, minijinja/tests/test_templates.rs
This makes a previously internal functionality public.
Fixes #494
=> Expose Value::from(error)

CHANGELOG.md, minijinja/src/compiler/lexer.rs, minijinja/tests/snapshots/test_lexer__lexer@lstrip-blocks-preserve.txt.snap, minijinja/tests/snapshots/test_lexer__lexer@lstrip-blocks.txt.snap
The implementation of `lstrip_blocks` accidentally also applied to variable expressions.
Fixes #496
=> Do not apply lstrip_blocks to expressions

CHANGELOG.md, minijinja-cli/Cargo.toml, minijinja-cli/README.md, minijinja-cli/src/cli.rs, minijinja-cli/src/main.rs, minijinja-cli/tests/test_basic.rs
Adds a `--syntax` flag to override syntax features such as delimiters.
=> Allow the CLI to override the syntax config

CHANGELOG.md, minijinja-py/python/minijinja/__init__.py, minijinja-py/src/environment.rs, minijinja-py/tests/test_basic.py, minijinja/src/syntax.rs
Fixes two missing cases and a bug in reconfiguring custom syntax.
=> Fix custom delimiters in Python

Cargo.lock, minijinja-contrib/Cargo.toml, minijinja/src/value/type_erase.rs
This method was previously not sound when the alignment of the type was larger than the necessary alignment for the atomic counters.
=> Route incref via vtable to avoid alignment issues

CHANGELOG.md, COMPATIBILITY.md, minijinja-cli/Cargo.toml, minijinja-cli/README.md, minijinja-cli/src/cli.rs, minijinja-cli/src/main.rs, minijinja-contrib/Cargo.toml, minijinja-contrib/src/lib.rs, minijinja-contrib/src/pycompat.rs, minijinja-contrib/tests/pycompat.rs
This adds `pycompat`, a new module to `minijinja-contrib`. It also adds a `--py-compat` flag to the CLI which enables it.
Once this is registered as an unknown method callback the engine supports functions such as `dict.keys` for better compatibility with Python based Jinja2 templates.
Refs #438
=> Adds python compatibility support to contrib

CHANGELOG.md, minijinja-contrib/src/pycompat.rs, minijinja-contrib/tests/pycompat.rs
This adds a few more common string methods.
=> Adds more string methods to pycompat

Cargo.toml
standalone binary goes from 50MB to 6MB
=> strip binaries for release

CHANGELOG.md, examples/build-script/Cargo.toml, examples/minimal/Cargo.toml, minijinja/Cargo.toml, minijinja/src/lib.rs
In anticipation of a version of #539
=> Trigger a warning if serde is disabled

CHANGELOG.md, minijinja/src/vm/context.rs, minijinja/src/vm/macro_object.rs, minijinja/src/vm/mod.rs, minijinja/tests/test_macros.rs
This changes how macros are resolving variables.  Previously if a macro did not enclose a value from the render scope it would only resolve down to the true global state passed to the environment.  This changes it so that the initial state passed to the context can also be used.
Refs #535
=> Allow macro state to resolve to the initial template context

CHANGELOG.md, minijinja-cli/Cargo.toml, minijinja-cli/README.md, minijinja-cli/src/cli.rs, minijinja-cli/src/main.rs, minijinja-contrib/src/lib.rs
This enables the `datetime` and `rand` features in the CLI.
=> Enable more minijinja-contrib features in the CLI

CHANGELOG.md, minijinja/src/vm/mod.rs, minijinja/tests/test_templates.rs
This resolves #551 . Please let me know if you want any changes made. This fix is the least disruptive one I could find. There may be a slight performance hit until the filters/tests are re-cached.
=> Flush local filter and test cache when processing `parent_instructions`

CHANGELOG.md, minijinja/src/value/deserialize.rs, minijinja/tests/test_value.rs
This fixes some bugs with the deserialize trait on `Value`.  I'm not sure if this covers all cases, but it fixes the cases reported.
Fixes #553
=> Fix a bug with deserializating enums

minijinja/src/compiler/codegen.rs
The code became hard to read with recent changes.
=> Convert PendingBlock to named structs

examples/generate-yaml/src/main.rs
Hi,
Currently, the "generate-yaml" example fails with:
```
thread 'main' panicked at examples/generate-yaml/src/main.rs:16:14:
called `Result::unwrap()` on an `Err` value: Error { kind: InvalidDelimiter }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Here is a simple fix.
=> example: nit

CHANGELOG.md, minijinja/src/value/mod.rs, minijinja/tests/inputs/slicing.txt, minijinja/tests/snapshots/test_templates__vm@slicing.txt.snap
This makes any iterable indexable.  They were already sliceable.
Fixes #564
=> Add support for indexing into iterables

CHANGELOG.md, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/tests/test_value.rs
This fixes the implementation of `PartialEq` for `Value`s containing maps and it slightly improves `Ord`.  `Ord` is not really fixed as the order of keys just does stupid stuff to the ordering.  I'm going to accept this for now because you're most likely not going to sort maps all that often.
Fixes #568
=> Fix the implementation of PartialEq for maps

CHANGELOG.md, minijinja/src/defaults.rs, minijinja/src/filters.rs, minijinja/src/value/mod.rs, minijinja/tests/inputs/groupby-filter.txt, minijinja/tests/snapshots/test_templates__vm@debug.txt.snap, minijinja/tests/snapshots/test_templates__vm@groupby-filter.txt.snap
This implements the `groupby` filter that was missing from Jinja2.
=> Implemented the groupby filter

CHANGELOG.md, minijinja/src/value/mod.rs, minijinja/tests/snapshots/test_templates__vm@coerce.txt.snap, minijinja/tests/snapshots/test_templates__vm@filters.txt.snap, minijinja/tests/test_value.rs
This changes the order of `Ord` to order strictly by value type first.  This now means that things order primarily by `ValueType` and secondarily by what the value type looks like.
This changes the order from earlier versions but addresses potential panics caused by the new sort function.
Fixes #577
=> Changed Ord to have a more consistent order

CHANGELOG.md, minijinja/src/tests.rs, minijinja/src/value/mod.rs
=> Add an Value::is_integer method

CHANGELOG.md, minijinja/src/value/merge_object.rs, minijinja/src/value/mod.rs, minijinja/tests/test_value.rs
=> Fix a regression in PartialEq/Eq in 2.3.0

Cargo.lock, README.md, benchmarks/Cargo.toml, benchmarks/benches/comparison.rs, benchmarks/rinja.toml
`rinja` is a `askama` fork made by me and another `askama` maintainer. More information about why and the main differences can be found [here](https://blog.guillaume-gomez.fr/articles/2024-07-31+docs.rs+switching+jinja+template+framework+from+tera+to+rinja).
Since `rinja` diverged "enough", I think it's worth adding it to the benchmarks list. By running it locally, I got:
```
Found 8 outliers among 100 measurements (8.00%)
8 (8.00%) high mild
cmp_render/minijinja    time:   [9.1311 µs 9.1745 µs 9.2243 µs]
Found 7 outliers among 100 measurements (7.00%)
6 (6.00%) high mild
1 (1.00%) high severe
cmp_render/tera         time:   [11.926 µs 11.945 µs 11.967 µs]
Found 12 outliers among 100 measurements (12.00%)
4 (4.00%) high mild
8 (8.00%) high severe
cmp_render/liquid       time:   [17.181 µs …
```
=> Add benchmarks for `rinja`

CHANGELOG.md, minijinja/src/value/argtypes.rs, minijinja/src/value/deserialize.rs
A complete fix is not really possible without breaking backwards compatibility, but these conversions are easy to guard.
Refs #596
=> Make Kwargs fail string conversions in ArgType

minijinja-cabi/example/Makefile
Fixes #612
Update the linking order in `minijinja-cabi/example/Makefile` to fix compilation errors on affected configurations.
* Change the linking order to place the source file `hello.c` before the library flag `-lminijinja_cabi`.
* Update the `cc` command to `cc -I../include ./hello.c -L../../target/release -lminijinja_cabi -o hello`.
=> Fix linking error in minijinja-cabi example on Debian GNU/Linux 11

CHANGELOG.md, minijinja/src/value/mod.rs, minijinja/tests/test_value.rs
This adds a `Value::from_bytes` method to directly create a bytes value, bypassing the serialization interface.  It also improves the debug printing of bytes meaningfully.
=> Added improved support for bytes

CHANGELOG.md, minijinja/src/value/argtypes.rs, minijinja/src/value/mod.rs, minijinja/src/value/ops.rs, minijinja/tests/test_value.rs
Playing with bytes a bit more showed some oddities in the current behavior.
=> Added better docs on bytes and unified implicit string conversions

minijinja/src/vm/mod.rs
...and make it hard to forget to add context again.
This hit us in https://github.com/axodotdev/cargo-dist when trying to enable strict undefined behavior.
The change I _do_ care about is using `ctx_ok!` in all branches of the vm evaluation.
I added a little trick where the `ok!` macro is shadowed, so if you accidentally use it again, rustc will yell at you:
Other ideas include.. shadowing `ok!` in the first place and changing every `ctx_ok!` invocation back to `ok!`, but eh, I had to pick one. Feel free to pick your favorite / take over this PR / do whatever it takes to get this merged, all I care is that our errors have debug info :) Thanks!
=> Add context for more "strict undefined behavior" cases

CHANGELOG.md, minijinja-cli/Cargo.toml, minijinja-cli/README.md, minijinja-cli/src/cli.rs, minijinja-cli/src/command.rs, minijinja-cli/tests/snapshots/test_basic__long_help.snap, minijinja-cli/tests/snapshots/test_basic__short_help.snap, minijinja-cli/tests/test_basic.rs
The doc says that all features are enabled by default, but it's not true: by default (and in the release binaries too) ini format support and shell completion aren't enabled + ini format is actually partially broken even when enabled (can't be specified in the command line).
This PR fixes the issue.
=> Enable all features by default in minijinja-cli

.github/workflows/build-wheels.yml
Turns out the `.cargo/config.toml` for the cli conflicts with the wheel builders.
=> Fix wheel builds

CHANGELOG.md, Cargo.lock, minijinja-cli/Cargo.toml, minijinja-contrib/Cargo.toml, minijinja-contrib/src/filters/mod.rs, minijinja-contrib/src/lib.rs, minijinja-contrib/tests/filters.rs
following Jinja2 implementation as described here
https://jinja.palletsprojects.com/en/stable/templates/#jinja-filters.wordwrap
=> add `wordwrap` filter

Cargo.lock, minijinja-cli/Cargo.toml, minijinja-contrib/Cargo.toml, minijinja-contrib/src/filters/mod.rs, minijinja-contrib/src/lib.rs, minijinja-contrib/tests/filters.rs
The `is_alphanumeric` function does not correctly handle Unicode marks, which leads to incorrect results in some cases. For example, the input `{{ helloाworld|wordcount }}` incorrectly returns `1`, whereas the correct result should be `2`.
Intentionally skipped updating the changelog as version 2.6.0 has not been released yet.
=> Fixes incorrect wordcount result when the string includes unicode marks

CHANGELOG.md, minijinja/src/filters.rs, minijinja/src/tests.rs, minijinja/src/value/argtypes.rs, minijinja/tests/test_environment.rs, minijinja/tests/test_undefined.rs
This is technically a behavior change but the current behavior clearly does not make sense and is in violation with Jinja2.
For the difference in behavior see $656.  After this change, there is no difference between `Value` and `&Value` as parameter other than the borrow difference.
Fixes #656
=> Pass arguments by reference when useful and fix an undefined bug

minijinja/src/vm/state.rs
This comment is slightly misleading, as it implies that the initial template context is not passed through to State inside macros which if true, would prevent some patterns (including the example date time filter in the filters documentation: https://docs.rs/minijinja/latest/minijinja/filters/index.html#filter-configuration, which relies on a TIME_FORMAT variable passed in in the render context).
Since https://github.com/mitsuhiko/minijinja/issues/535 (released in v2.1.0), this is no longer how this works.
This updates the `State::lookup` docs to clarify the initial render context is also always available.
=> Update state::lookup documentation to reflect updated capture behaviour

CHANGELOG.md, minijinja-cli/src/command.rs, minijinja-cli/tests/snapshots/test_basic__long_help.snap, minijinja/src/value/mod.rs, minijinja/src/value/serialize.rs, minijinja/tests/test_templates.rs
The latest serde release changes some internals (https://github.com/serde-rs/serde/pull/2786) which makes flatten accidentally work on our value handle in-band signalling.  This works around this by using a different code path in serde.
Refs #222
(Also fix some old typos that now fail CI)
=> Fix flatten error condition for latest serde

CHANGELOG.md, minijinja/src/filters.rs
This improves `|items` to not allocate a list internally.  This was overlooked when the improvements were made that enabled iterators.
=> Improve items to not allocate a list

CONTRIBUTING.md
Considering you are long past minijinja 1 I assume this section is safe to remove
=> docs: remove minijinja1 section from contributing guidelines

CHANGELOG.md, Cargo.lock, minijinja-cli/Cargo.toml, minijinja-cli/src/cli.rs, minijinja-cli/src/config.rs
This moves minijinja-cli back to the deprecated `serde_yaml`.
Refs https://github.com/BurntSushi/jiff/pull/225
=> Use deprecated serde_yaml in cli

CHANGELOG.md, minijinja/src/compiler/ast.rs, minijinja/src/compiler/codegen.rs, minijinja/tests/inputs/err_strict_undefined_for.txt, minijinja/tests/inputs/err_strict_undefined_for_filter.txt, minijinja/tests/inputs/err_strict_undefined_if.txt, minijinja/tests/inputs/err_strict_undefined_print.txt, minijinja/tests/snapshots/test_templates__vm@err_strict_undefined_for.txt.snap, minijinja/tests/snapshots/test_templates__vm@err_strict_undefined_for_filter.txt.snap, minijinja/tests/snapshots/test_templates__vm@err_strict_undefined_if.txt.snap, minijinja/tests/snapshots/test_templates__vm@err_strict_undefined_print.txt.snap, minijinja/tests/snapshots/test_templates__vm@loop-recursion-error.txt.snap, minijinja/tests/snapshots/test_templates__vm@loop_over_non_iterable.txt.snap, minijinja/tests/test_templates.rs
MiniJinja did not report proper information about what is undefined
```
undefined value (in err_strict_undefined_if.txt:1)
------------------------- err_strict_undefined_if.txt -------------------------
1 > {% if undefined_value %}
2 |     ...
3 | {% endif %}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
No referenced variables
-------------------------------------------------------------------------------
```
```
undefined value (in err_strict_undefined_if.txt:1)
------------------------- err_strict_undefined_if.txt -------------------------
1 > {% if undefined_value %}
i       ^^^^^^^^^^^^^^^ undefined value
2 |     ...
3 | {% endif %}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
No referenced variables …
```
=> Fix undefineds in some places not reporting proper errors

CHANGELOG.md, minijinja/src/compiler/codegen.rs, minijinja/src/environment.rs, minijinja/src/filters.rs, minijinja/src/functions.rs, minijinja/src/syntax.rs, minijinja/src/utils.rs, minijinja/src/value/argtypes.rs, minijinja/src/value/deserialize.rs, minijinja/src/value/mod.rs, minijinja/src/value/ops.rs, minijinja/src/vm/mod.rs, minijinja/tests/test_undefined.rs
This makes to changes to Jinja2
1. The implicit `else` branch in an if expression will evaluate to a new `SilentUndefined` representation.  This is invisible from the perspective of an engine user.  Jinja2 does something similar where it will always use a default `Undefined` object which does not error on iteration of truthiness checks.
2. Adds a new `SemiStrict` undefined behavior which is like `Strict` but permits boolean evaluations.  Eg: `{% if undefined %}` does not error.
This addresses #680
=> Add SemiStrict and improve Jinja2 compatibility

CHANGELOG.md, examples/hello/src/main.rs, minijinja/src/value/deserialize.rs
This provides much better feedback to users who are trying to use a type that does not implement `Deserialize` with `ViaDeserialize`. Previously, the error would appear when trying to use a function or type that itself uses `ViaDeserialize`, e.g. when calling `Environment::add_function` on a function with a parameter using `ViaDeserialize` on a type that does not implement `Deserialize`. For example:
```
error[E0277]: the trait bound `for<'a, 'b, 'c> fn(ViaDeserialize<&'a Page<'b>>, ViaDeserialize<&'c data::config::Config>) -> std::string::String {url_for}: Function<_, _>` is not satisfied
--> src/templates/functions.rs:66:32
|
66  |    env.add_function("url_for", url_for);
|        ------------            ^^^^^^^ the trait `Function<_, _>` is not implemented for fn item …
```
=> Check that types passed to `ViaDeserialize` implement `Serialize`

CHANGELOG.md, minijinja-contrib/src/filters/mod.rs, minijinja-contrib/src/globals.rs, minijinja-contrib/src/rand.rs, minijinja-contrib/tests/globals.rs
Previously the rng when seeded would always return the same random number.  This fixes it.
=> Fix random numbers not advancing the rng when seeded

.vscode/settings.json, CHANGELOG.md, minijinja-py/src/typeconv.rs, minijinja-py/tests/test_basic.py, minijinja/src/value/mod.rs, minijinja/src/value/object.rs, minijinja/tests/test_value.rs
This adds a new `Object::custom_cmp` method to allow limited custom comparisons.  This will allow python objects to be compared against matching types.  This will *not* allow comparisons between objects of different types.  It also requires total order so the python bindings will panic if a sort is attempted of sequences that do not allow total order.
Refs #703
=> Allow objects to influence how they are compared

minijinja/src/lib.rs
warning: doc list item overindented
--> minijinja/src/lib.rs:181:5
|
181 | //!    tags.
|     ^^^ help: try using `  ` (2 spaces)
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items
= note: `#[warn(clippy::doc_overindented_list_items)]` on by default
=> clippy:doc_overindented_list_items

CHANGELOG.md, Cargo.lock, Cargo.toml, minijinja-py/Cargo.toml, minijinja-py/README.md, minijinja-py/src/environment.rs, minijinja-py/src/error_support.rs, minijinja-py/src/state.rs, minijinja-py/src/typeconv.rs, minijinja-py/tests/test_basic.py
This releases the lock around template rendering to get rid of a deadlock.
It's still a bad idea to render from the same environment from multiple threads as only one template can render at the time in Python due to the internal lock.
Fixes #716
=> Fix python locking

CHANGELOG.md, minijinja/src/compiler/meta.rs, minijinja/tests/test_templates.rs
`caller` was not handled correctly for undeclared variable finding.
Refs #715
=> Fix caller being marked as undeclared

CHANGELOG.md, minijinja/src/compiler/parser.rs, minijinja/tests/parser-inputs/string-implicit-concat.txt, minijinja/tests/snapshots/test_parser__parser@string-implicit-concat.txt.snap
String literals should behave the same regardless of whether they contain escape sequences. 
This PR fixes the string literal "implicit concat" rule to account for `Token::String`s.
=> Parser: fix implicit concat for allocated strings

minijinja/src/compiler/ast.rs, minijinja/src/compiler/lexer.rs, minijinja/src/compiler/parser.rs, minijinja/src/compiler/tokens.rs, minijinja/src/value/mod.rs, minijinja/src/vm/context.rs, minijinja/src/vm/mod.rs
This improves the speed of parsing by about 12%.
=> Reduce the size of tokens and ast nodes

CHANGELOG.md, minijinja/src/compiler/ast.rs, minijinja/src/compiler/codegen.rs, minijinja/tests/test_compiler.rs
Some operations on constant values are converted into constants at codegen time.
=> Implement constant folding optimization

CHANGELOG.md, minijinja/src/compiler/codegen.rs, minijinja/src/compiler/instructions.rs, minijinja/src/compiler/lexer.rs, minijinja/src/compiler/tokens.rs, minijinja/src/vm/loop_object.rs, minijinja/src/vm/mod.rs, minijinja/src/vm/state.rs
This now uses `u16` for column and line numbers which should be enough for any real world template and uses `u32` for addresses on all architectures.
=> Use smaller integers for spans and addresses

CHANGELOG.md, minijinja/src/value/mod.rs, minijinja/tests/test_environment.rs
This fixes a bug that an `unknown_method_callback` would not trigger the default error handling for unknown methods.  Now the error message is properly filled in if that callback returns `UnknownMethod`.
=> Fix unknown_method_callback error reporting

CHANGELOG.md, minijinja/src/macros.rs, minijinja/src/value/merge_object.rs, minijinja/src/value/mod.rs
This exposes the underlying functionality of the `context!` macro has a dynamic merge function.  This came up when trying to solve for #744.
This also fixes `enumerate` being completely broken if non map objects were passed to it (mostly sequences).
=> Add dynamic merge function

minijinja-cli/src/cli.rs, minijinja-cli/src/command.rs, minijinja-cli/tests/snapshots/test_basic__long_help.snap, minijinja-cli/tests/snapshots/test_basic__short_help.snap, minijinja-cli/tests/test_basic.rs, minijinja/src/macros.rs, minijinja/src/value/merge_object.rs
Fixes #744 
This also changes the order of `merge_maps` to be what one would actually expect.  Since that function was just added it should be fine to change it here.
=> Add support for multiple data files to the CLI

CHANGELOG.md, minijinja-cabi/example/hello.c, minijinja-cabi/include/minijinja.h, minijinja-cabi/src/utils.rs, minijinja-cabi/src/value.rs
Adds a convenience method to borrow bytes from strings or bytes values.
Refs #749
=> Add an as_bytes function for the C-ABI

Cargo.lock, minijinja-contrib/Cargo.toml
Has some meaningful fixes that make it more useful.
Replaces #747
=> Bump textwrap dependency to 0.16.2

CHANGELOG.md, minijinja/src/compiler/parser.rs, minijinja/tests/parser-inputs/imports.txt, minijinja/tests/snapshots/test_parser__parser@imports.txt.snap
The context markers were not implemented for `{% import %}` and `{% from ... import %}`.
Fixes #758
=> Correctly handle with/without context for imports

CHANGELOG.md, Cargo.lock, minijinja-py/Cargo.toml, minijinja-py/python/minijinja/__init__.py, minijinja-py/src/environment.rs, minijinja-py/tests/test_basic.py
The python bindings did not enable the `pycompat` mode before.  This was assumed to be okay since most types are just python types.  However this does cause confusing because dictionaries created within the minijinja engine will not have those methods.
This now enables this mode by default which should resolve most of those inconsistencies.  It won't fix everything though since not all methods are a perfect match.
This also enables the contrib module which adds a few methods missing.
Fixes #766
=> Enable pycompat and contrib in python

minijinja/src/tests.rs
The documentation for the tests module referenced `is_defined`, but explained it as "check if the value is indeed an odd number". Corrected the example to use `is odd`, and the function name to `is_odd`.
Could have corrected the wording too, but the next example shows even/odd, so correcting the test and the function name felt more appropriate.
=> Fix the function reference in the src/tests docs

CHANGELOG.md, minijinja-cabi/include/minijinja.h, minijinja-cabi/src/error.rs
A simple getter, not sure if it would be preferable to separate the source debug info or not
Context: https://github.com/mitsuhiko/minijinja/discussions/748#discussioncomment-12440741
=> cabi: Add getter for error debug info

minijinja/src/compiler/codegen.rs, minijinja/src/value/ops.rs, minijinja/tests/inputs/slicing.txt, minijinja/tests/snapshots/test_templates__vm@slicing.txt.snap
This fixes an issue introduced by the last change where the bytecode did not pass `None` as intended.  It also avoids `successors` which does not have a length hint.
=> Fix a big in reverse slicing and add a test

CHANGELOG.md, minijinja/src/environment.rs, minijinja/src/functions.rs, minijinja/src/value/mod.rs
Hi there :wave: unfortunately minijinja currently relies on a type system bug. This code will break with the `-Znext-solver`.
Let's look at the relevant section of the minimization in https://github.com/rust-lang/trait-system-refactor-initiative/issues/195#issuecomment-2851196452 [[godbolt](https://rust.godbolt.org/z/PcoMbjMdh)]:
```rust
trait Arg<'a> {
type Output;
}
trait Filter<A> {}
impl<A, F: FnMut(A)> Filter<A> for F {}
fn inspect_values<F, A>(_: F)
where
A: for<'a> Arg<'a>,
F: for<'a> Filter<<A as Arg<'a>>::Output> + Filter<A>,
{
}
fn generic_caller<F, A>(f: F)
where
A: for<'a> Arg<'a>,
F: for<'a> Filter<<A as Arg<'a>>::Output> + Filter<A>,
{
inspect_values(f)
}
```
The call to `inspect_values` starts out with `A` and `F` being unconstrained inference variables, let's call them …
=> fix regression with the next-generation trait solver

minijinja/src/filters.rs, minijinja/tests/test_filters.rs
Currently, the `sort` filter allows sorting objects using a custom key via the "attribute" keyword argument, which is limited to fetching a single field from the object and using that as the key. Sometimes it is useful to sort objects using multiple keys, or a composite key made of multiple fields of the object. Add a new keyword argument "keys" to support such keys.
Now, you can not only sort cities by their name ...
`{{ cities|sort(attribute="name") }}`
... but also sort cities with the same name by their country:
`{{ cities|sort(keys=["name", "country"]) }}`
=> Add multiple-key support in the sort filter
